2025-10-17 13:42:35,454 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'init' at Fri, 17 Oct 2025 13:42:35 +0000. Up 7.04 seconds.
2025-10-17 13:42:35,454 - main.py[DEBUG]: No kernel command line url found.
2025-10-17 13:42:35,454 - main.py[DEBUG]: Closing stdin.
2025-10-17 13:42:35,456 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=False)
2025-10-17 13:42:35,457 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-10-17 13:42:35,461 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=False)
2025-10-17 13:42:35,461 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-10-17 13:42:35,463 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-instance (recursive=False)
2025-10-17 13:42:35,464 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-10-17 13:42:35,467 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-once (recursive=False)
2025-10-17 13:42:35,467 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-10-17 13:42:35,471 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-boot (recursive=False)
2025-10-17 13:42:35,472 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2025-10-17 13:42:35,476 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/vendor (recursive=False)
2025-10-17 13:42:35,477 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-10-17 13:42:35,484 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/seed (recursive=False)
2025-10-17 13:42:35,484 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-10-17 13:42:35,492 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances (recursive=False)
2025-10-17 13:42:35,493 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-10-17 13:42:35,502 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/handlers (recursive=False)
2025-10-17 13:42:35,502 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2025-10-17 13:42:35,513 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem (recursive=False)
2025-10-17 13:42:35,513 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data (recursive=False)
2025-10-17 13:42:35,514 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init (recursive=True)
2025-10-17 13:42:35,514 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/sem (recursive=False)
2025-10-17 13:42:35,515 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2025-10-17 13:42:35,516 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2025-10-17 13:42:35,516 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2025-10-17 13:42:35,517 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 0:4
2025-10-17 13:42:35,517 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 3 bytes
2025-10-17 13:42:35,518 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2025-10-17 13:42:35,518 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2025-10-17 13:42:35,519 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2025-10-17 13:42:35,523 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2025-10-17 13:42:35,526 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2025-10-17 13:42:35,536 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2025-10-17 13:42:35,540 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2025-10-17 13:42:35,542 - stages.py[DEBUG]: no cache found
2025-10-17 13:42:35,547 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2025-10-17 13:42:35,547 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-10-17 13:42:35,577 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-10-17 13:42:35,577 - __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2025-10-17 13:42:35,583 - __init__.py[DEBUG]: Searching for network data source in: ['DataSourceEc2', 'DataSourceNone']
2025-10-17 13:42:35,583 - handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
2025-10-17 13:42:35,583 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
2025-10-17 13:42:35,583 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2025-10-17 13:42:35,583 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2025-10-17 13:42:35,583 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_uuid
2025-10-17 13:42:35,583 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2025-10-17 13:42:35,583 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2025-10-17 13:42:35,583 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2025-10-17 13:42:35,584 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
2025-10-17 13:42:35,584 - util.py[DEBUG]: Skipping DNS checks of IP address 169.254.169.254
2025-10-17 13:42:35,584 - util.py[DEBUG]: Resolving URL: http://169.254.169.254:80 took 0.000 seconds
2025-10-17 13:42:35,584 - util.py[DEBUG]: Skipping DNS checks of IP address fd00:ec2::254
2025-10-17 13:42:35,584 - util.py[DEBUG]: Resolving URL: http://[fd00:ec2::254]:80 took 0.000 seconds
2025-10-17 13:42:35,584 - DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
2025-10-17 13:42:35,585 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2025-10-17 13:42:35,589 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/latest/api/token (200, 56b) after 1 attempts
2025-10-17 13:42:35,589 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254:80'
2025-10-17 13:42:35,590 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,591 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2025-10-17 13:42:35,591 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2021-03-23
2025-10-17 13:42:35,592 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/user-data' with {'url': 'http://169.254.169.254:80/2021-03-23/user-data', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,594 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/user-data (200, 2450b) after 1 attempts
2025-10-17 13:42:35,594 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,596 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ (200, 305b) after 1 attempts
2025-10-17 13:42:35,596 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,597 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
2025-10-17 13:42:35,598 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,599 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami (200, 4b) after 1 attempts
2025-10-17 13:42:35,599 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,601 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2025-10-17 13:42:35,601 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,603 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/ (200, 12b) after 1 attempts
2025-10-17 13:42:35,603 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,604 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/ (200, 17b) after 1 attempts
2025-10-17 13:42:35,604 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,606 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history (200, 2b) after 1 attempts
2025-10-17 13:42:35,606 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,608 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
2025-10-17 13:42:35,608 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,610 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/ (200, 26b) after 1 attempts
2025-10-17 13:42:35,610 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,612 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/info (200, 216b) after 1 attempts
2025-10-17 13:42:35,612 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,614 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ (200, 4b) after 1 attempts
2025-10-17 13:42:35,614 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,616 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
2025-10-17 13:42:35,616 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,618 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
2025-10-17 13:42:35,618 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,619 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/ (200, 7b) after 1 attempts
2025-10-17 13:42:35,620 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,626 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2025-10-17 13:42:35,626 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,628 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/ (200, 11b) after 1 attempts
2025-10-17 13:42:35,628 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,632 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2025-10-17 13:42:35,633 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,635 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2025-10-17 13:42:35,635 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,637 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/ (200, 230b) after 1 attempts
2025-10-17 13:42:35,637 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/ipv4-associations/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/ipv4-associations/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,639 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/ipv4-associations/ (200, 13b) after 1 attempts
2025-10-17 13:42:35,639 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/ipv4-associations/13.220.141.77' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/ipv4-associations/13.220.141.77', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,641 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/ipv4-associations/13.220.141.77 (200, 12b) after 1 attempts
2025-10-17 13:42:35,641 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/device-number' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/device-number', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,643 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/device-number (200, 1b) after 1 attempts
2025-10-17 13:42:35,643 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/interface-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/interface-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,645 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/interface-id (200, 21b) after 1 attempts
2025-10-17 13:42:35,645 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,647 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/local-hostname (200, 28b) after 1 attempts
2025-10-17 13:42:35,647 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/local-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/local-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,649 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/local-ipv4s (200, 12b) after 1 attempts
2025-10-17 13:42:35,649 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,651 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/mac (200, 17b) after 1 attempts
2025-10-17 13:42:35,651 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/owner-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/owner-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,654 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/owner-id (200, 12b) after 1 attempts
2025-10-17 13:42:35,654 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,656 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/public-hostname (200, 41b) after 1 attempts
2025-10-17 13:42:35,656 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/public-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/public-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,658 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/public-ipv4s (200, 13b) after 1 attempts
2025-10-17 13:42:35,658 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/security-group-ids' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/security-group-ids', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,660 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/security-group-ids (200, 20b) after 1 attempts
2025-10-17 13:42:35,660 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,662 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/security-groups (200, 56b) after 1 attempts
2025-10-17 13:42:35,662 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/subnet-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/subnet-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,665 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/subnet-id (200, 24b) after 1 attempts
2025-10-17 13:42:35,665 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/subnet-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,667 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/subnet-ipv4-cidr-block (200, 13b) after 1 attempts
2025-10-17 13:42:35,667 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/vpc-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/vpc-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,668 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/vpc-id (200, 21b) after 1 attempts
2025-10-17 13:42:35,669 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/vpc-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,670 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
2025-10-17 13:42:35,670 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/vpc-ipv4-cidr-blocks', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,673 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:f2:f0:1f:42:ff/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
2025-10-17 13:42:35,673 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,675 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/ (200, 45b) after 1 attempts
2025-10-17 13:42:35,675 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,677 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone (200, 10b) after 1 attempts
2025-10-17 13:42:35,677 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,679 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id (200, 8b) after 1 attempts
2025-10-17 13:42:35,679 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,681 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/region (200, 9b) after 1 attempts
2025-10-17 13:42:35,681 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,683 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/ (200, 16b) after 1 attempts
2025-10-17 13:42:35,683 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,685 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/domain (200, 13b) after 1 attempts
2025-10-17 13:42:35,685 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,687 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/partition (200, 3b) after 1 attempts
2025-10-17 13:42:35,687 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,689 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-id (200, 21b) after 1 attempts
2025-10-17 13:42:35,690 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,691 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index (200, 1b) after 1 attempts
2025-10-17 13:42:35,692 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,694 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2025-10-17 13:42:35,694 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,696 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/hostname (200, 28b) after 1 attempts
2025-10-17 13:42:35,696 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,698 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-action (200, 4b) after 1 attempts
2025-10-17 13:42:35,698 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,700 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2025-10-17 13:42:35,700 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,703 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle (200, 9b) after 1 attempts
2025-10-17 13:42:35,703 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,705 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-type (200, 8b) after 1 attempts
2025-10-17 13:42:35,705 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,709 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-hostname (200, 28b) after 1 attempts
2025-10-17 13:42:35,709 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,711 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4 (200, 12b) after 1 attempts
2025-10-17 13:42:35,711 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,713 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/mac (200, 17b) after 1 attempts
2025-10-17 13:42:35,713 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/profile' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/profile', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,715 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/profile (200, 11b) after 1 attempts
2025-10-17 13:42:35,715 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,717 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-hostname (200, 41b) after 1 attempts
2025-10-17 13:42:35,717 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,719 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4 (200, 13b) after 1 attempts
2025-10-17 13:42:35,719 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,721 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/reservation-id (200, 19b) after 1 attempts
2025-10-17 13:42:35,721 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,723 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/security-groups (200, 56b) after 1 attempts
2025-10-17 13:42:35,723 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,727 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity (200, 32b) after 1 attempts
2025-10-17 13:42:35,727 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,729 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document (200, 476b) after 1 attempts
2025-10-17 13:42:35,729 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,731 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7 (200, 1171b) after 1 attempts
2025-10-17 13:42:35,731 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,734 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048 (200, 1491b) after 1 attempts
2025-10-17 13:42:35,734 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2025-10-17 13:42:35,736 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2025-10-17 13:42:35,736 - util.py[DEBUG]: Crawl of metadata service took 0.152 seconds
2025-10-17 13:42:35,738 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-aws - wb: [644] 4 bytes
2025-10-17 13:42:35,739 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2025-10-17 13:42:35,739 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2025-10-17 13:42:35,740 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-aws'
2025-10-17 13:42:35,740 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmp1qnjr9vd) - w: [600] 11954 bytes/chars
2025-10-17 13:42:35,741 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpfjfe8tdx) - w: [644] 7812 bytes/chars
2025-10-17 13:42:35,741 - handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: found network data from DataSourceEc2
2025-10-17 13:42:35,741 - stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
2025-10-17 13:42:35,741 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-10-17 13:42:35,742 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2025-10-17 13:42:35,742 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,748 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2025-10-17 13:42:35,749 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2025-10-17 13:42:35,749 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,749 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2025-10-17 13:42:35,749 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2025-10-17 13:42:35,749 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,751 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-10-17 13:42:35,751 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-10-17 13:42:35,751 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,754 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2025-10-17 13:42:35,754 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2025-10-17 13:42:35,754 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,755 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-10-17 13:42:35,755 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,755 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-10-17 13:42:35,756 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2025-10-17 13:42:35,756 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-0d445e9a3d91a5047'
2025-10-17 13:42:35,757 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047 (recursive=True)
2025-10-17 13:42:35,760 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/handlers (recursive=False)
2025-10-17 13:42:35,761 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047 (recursive=True)
2025-10-17 13:42:35,764 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/scripts (recursive=False)
2025-10-17 13:42:35,765 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047 (recursive=True)
2025-10-17 13:42:35,769 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem (recursive=False)
2025-10-17 13:42:35,769 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-0d445e9a3d91a5047/datasource (quiet=False)
2025-10-17 13:42:35,770 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/datasource - wb: [644] 29 bytes
2025-10-17 13:42:35,770 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/datasource (recursive=False)
2025-10-17 13:42:35,771 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/datasource (recursive=False)
2025-10-17 13:42:35,771 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
2025-10-17 13:42:35,771 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2025-10-17 13:42:35,772 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2025-10-17 13:42:35,772 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2025-10-17 13:42:35,772 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2025-10-17 13:42:35,772 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2025-10-17 13:42:35,773 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2025-10-17 13:42:35,773 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2025-10-17 13:42:35,774 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2025-10-17 13:42:35,774 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2025-10-17 13:42:35,774 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2025-10-17 13:42:35,775 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2025-10-17 13:42:35,775 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2025-10-17 13:42:35,776 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2025-10-17 13:42:35,777 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 12525 bytes
2025-10-17 13:42:35,777 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/obj.pkl (recursive=False)
2025-10-17 13:42:35,778 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/obj.pkl (recursive=False)
2025-10-17 13:42:35,778 - main.py[DEBUG]: [net] init will now be targeting instance id: i-0d445e9a3d91a5047. new=True
2025-10-17 13:42:35,778 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-10-17 13:42:35,778 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2025-10-17 13:42:35,778 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,785 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2025-10-17 13:42:35,785 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2025-10-17 13:42:35,785 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,786 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2025-10-17 13:42:35,786 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2025-10-17 13:42:35,786 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,787 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-10-17 13:42:35,787 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-10-17 13:42:35,787 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,790 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2025-10-17 13:42:35,790 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2025-10-17 13:42:35,790 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,791 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-10-17 13:42:35,791 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,792 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-10-17 13:42:35,793 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-10-17 13:42:35,793 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2025-10-17 13:42:35,793 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-10-17 13:42:35,793 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2025-10-17 13:42:35,793 - util.py[DEBUG]: Reading from /sys/class/net/ens5/name_assign_type (quiet=False)
2025-10-17 13:42:35,793 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/name_assign_type
2025-10-17 13:42:35,793 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-10-17 13:42:35,793 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2025-10-17 13:42:35,793 - util.py[DEBUG]: Reading from /sys/class/net/ens5/carrier (quiet=False)
2025-10-17 13:42:35,793 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/carrier
2025-10-17 13:42:35,793 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2025-10-17 13:42:35,793 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2025-10-17 13:42:35,793 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2025-10-17 13:42:35,793 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2025-10-17 13:42:35,794 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2025-10-17 13:42:35,794 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2025-10-17 13:42:35,794 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2025-10-17 13:42:35,794 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2025-10-17 13:42:35,794 - util.py[DEBUG]: Reading from /sys/class/net/ens5/addr_assign_type (quiet=False)
2025-10-17 13:42:35,794 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/addr_assign_type
2025-10-17 13:42:35,794 - util.py[DEBUG]: Reading from /sys/class/net/ens5/uevent (quiet=False)
2025-10-17 13:42:35,794 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/ens5/uevent
2025-10-17 13:42:35,794 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2025-10-17 13:42:35,794 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2025-10-17 13:42:35,794 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2025-10-17 13:42:35,794 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens5/device/device
2025-10-17 13:42:35,794 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2025-10-17 13:42:35,794 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type
2025-10-17 13:42:35,794 - util.py[DEBUG]: Reading from /sys/class/net/ens5/type (quiet=False)
2025-10-17 13:42:35,794 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/type
2025-10-17 13:42:35,794 - stages.py[DEBUG]: network config disabled by system_cfg
2025-10-17 13:42:35,794 - stages.py[INFO]: network config is disabled by system_cfg
2025-10-17 13:42:35,794 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2025-10-17 13:42:35,795 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2025-10-17 13:42:35,795 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/user-data.txt - wb: [600] 2450 bytes
2025-10-17 13:42:35,795 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/user-data.txt (recursive=False)
2025-10-17 13:42:35,796 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/user-data.txt (recursive=False)
2025-10-17 13:42:35,797 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,800 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/user-data.txt.i - wb: [600] 2472 bytes
2025-10-17 13:42:35,801 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/user-data.txt.i (recursive=False)
2025-10-17 13:42:35,801 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/user-data.txt.i (recursive=False)
2025-10-17 13:42:35,802 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/vendor-data.txt - wb: [600] 0 bytes
2025-10-17 13:42:35,803 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/vendor-data.txt (recursive=False)
2025-10-17 13:42:35,803 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/vendor-data.txt (recursive=False)
2025-10-17 13:42:35,805 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/vendor-data.txt.i - wb: [600] 308 bytes
2025-10-17 13:42:35,805 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/vendor-data.txt.i (recursive=False)
2025-10-17 13:42:35,806 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/vendor-data.txt.i (recursive=False)
2025-10-17 13:42:35,806 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/vendor-data2.txt - wb: [600] 0 bytes
2025-10-17 13:42:35,817 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/vendor-data2.txt (recursive=False)
2025-10-17 13:42:35,818 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/vendor-data2.txt (recursive=False)
2025-10-17 13:42:35,819 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/vendor-data2.txt.i - wb: [600] 308 bytes
2025-10-17 13:42:35,829 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/vendor-data2.txt.i (recursive=False)
2025-10-17 13:42:35,830 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/vendor-data2.txt.i (recursive=False)
2025-10-17 13:42:35,831 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-10-17 13:42:35,831 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-172-31-3-252.ec2.internal (ip-172-31-3-252)
2025-10-17 13:42:35,831 - subp.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-172-31-3-252.ec2.internal'] with allowed return codes [0] (shell=False, capture=True)
2025-10-17 13:42:35,941 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-172-31-3-252.ec2.internal
2025-10-17 13:42:35,941 - subp.py[DEBUG]: Running command ['hostname', 'ip-172-31-3-252.ec2.internal'] with allowed return codes [0] (shell=False, capture=True)
2025-10-17 13:42:35,966 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmpzzteqkna) - w: [644] 76 bytes/chars
2025-10-17 13:42:35,967 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/consume_data - wb: [644] 25 bytes
2025-10-17 13:42:35,967 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/consume_data (recursive=False)
2025-10-17 13:42:35,969 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/consume_data (recursive=False)
2025-10-17 13:42:35,969 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/consume_data'>)
2025-10-17 13:42:35,969 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2025-10-17 13:42:35,969 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2025-10-17 13:42:35,970 - stages.py[DEBUG]: Added default handler for {'text/cloud-config-jsonp', 'text/cloud-config'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2025-10-17 13:42:35,970 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2025-10-17 13:42:35,970 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2025-10-17 13:42:35,970 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2025-10-17 13:42:35,970 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2025-10-17 13:42:35,970 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2025-10-17 13:42:35,970 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2025-10-17 13:42:35,970 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2025-10-17 13:42:35,971 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2025-10-17 13:42:35,971 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2025-10-17 13:42:35,971 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2025-10-17 13:42:35,971 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2025-10-17 13:42:35,971 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2025-10-17 13:42:35,971 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2025-10-17 13:42:35,971 - __init__.py[DEBUG]: {'Content-Type': 'text/cloud-config; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="cloud-config.txt"'}
2025-10-17 13:42:35,971 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, cloud-config.txt, 3) with frequency once-per-instance
2025-10-17 13:42:35,971 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,972 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
2025-10-17 13:42:35,972 - __init__.py[DEBUG]: {'Content-Type': 'text/x-shellscript; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="user-data.txt"'}
2025-10-17 13:42:35,972 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, user-data.txt, 2) with frequency once-per-instance
2025-10-17 13:42:35,972 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/user-data.txt - wb: [700] 1801 bytes
2025-10-17 13:42:35,973 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/scripts/user-data.txt (recursive=False)
2025-10-17 13:42:35,974 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/scripts/user-data.txt (recursive=False)
2025-10-17 13:42:35,975 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2025-10-17 13:42:35,975 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/cloud-config.txt - wb: [600] 154 bytes
2025-10-17 13:42:35,976 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/cloud-config.txt (recursive=False)
2025-10-17 13:42:35,976 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/cloud-config.txt (recursive=False)
2025-10-17 13:42:35,977 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2025-10-17 13:42:35,977 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2025-10-17 13:42:35,977 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2025-10-17 13:42:35,977 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2025-10-17 13:42:35,977 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2025-10-17 13:42:35,977 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2025-10-17 13:42:35,977 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2025-10-17 13:42:35,977 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2025-10-17 13:42:35,977 - stages.py[DEBUG]: no vendordata from datasource
2025-10-17 13:42:35,977 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2025-10-17 13:42:35,977 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2025-10-17 13:42:35,977 - stages.py[DEBUG]: no vendordata2 from datasource
2025-10-17 13:42:35,977 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2025-10-17 13:42:35,977 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2025-10-17 13:42:35,978 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2025-10-17 13:42:35,978 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,984 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2025-10-17 13:42:35,984 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2025-10-17 13:42:35,984 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,985 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2025-10-17 13:42:35,985 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2025-10-17 13:42:35,985 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,987 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2025-10-17 13:42:35,987 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2025-10-17 13:42:35,987 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,989 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2025-10-17 13:42:35,989 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2025-10-17 13:42:35,989 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,991 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2025-10-17 13:42:35,991 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,991 - util.py[DEBUG]: loaded blob returned None, returning default.
2025-10-17 13:42:35,991 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-10-17 13:42:35,991 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-10-17 13:42:35,991 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:35,992 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:35,993 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:36,125 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2025-10-17 13:42:36,125 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2025-10-17 13:42:36,125 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2025-10-17 13:42:36,128 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2025-10-17 13:42:36,129 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 16674 bytes
2025-10-17 13:42:36,130 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/obj.pkl (recursive=False)
2025-10-17 13:42:36,131 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/obj.pkl (recursive=False)
2025-10-17 13:42:36,132 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2025-10-17 13:42:36,132 - main.py[DEBUG]: no di_report found in config.
2025-10-17 13:42:36,134 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:36,134 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:36,136 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:36,137 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:36,139 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:36,139 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:36,141 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:36,141 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:36,144 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:36,144 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:36,148 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:36,148 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:36,150 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:36,150 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:36,165 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:36,165 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:36,168 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:36,168 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:36,171 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:36,171 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:36,173 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:36,173 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:36,175 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:36,175 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:36,177 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:36,177 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:36,180 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:36,180 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:36,183 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:36,183 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:36,185 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:36,186 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:36,187 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-10-17 13:42:36,188 - modules.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2025-10-17 13:42:36,188 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2025-10-17 13:42:36,188 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7fce6710a910>)
2025-10-17 13:42:36,188 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2025-10-17 13:42:36,189 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2025-10-17 13:42:36,189 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2025-10-17 13:42:36,189 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2025-10-17 13:42:36,189 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_seed_random - wb: [644] 24 bytes
2025-10-17 13:42:36,189 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_seed_random (recursive=False)
2025-10-17 13:42:36,190 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_seed_random (recursive=False)
2025-10-17 13:42:36,191 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_seed_random'>)
2025-10-17 13:42:36,191 - cc_seed_random.py[DEBUG]: no command provided
2025-10-17 13:42:36,191 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2025-10-17 13:42:36,191 - modules.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always
2025-10-17 13:42:36,191 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
2025-10-17 13:42:36,191 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7fce6710a910>)
2025-10-17 13:42:36,191 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
2025-10-17 13:42:36,191 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
2025-10-17 13:42:36,191 - modules.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2025-10-17 13:42:36,191 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
2025-10-17 13:42:36,191 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_write_files - wb: [644] 25 bytes
2025-10-17 13:42:36,192 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_write_files (recursive=False)
2025-10-17 13:42:36,193 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_write_files (recursive=False)
2025-10-17 13:42:36,193 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_write_files'>)
2025-10-17 13:42:36,193 - cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
2025-10-17 13:42:36,193 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
2025-10-17 13:42:36,193 - modules.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_metadata.py'>) with frequency once-per-instance
2025-10-17 13:42:36,194 - handlers.py[DEBUG]: start: init-network/config-write-metadata: running config-write-metadata with frequency once-per-instance
2025-10-17 13:42:36,194 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_write_metadata - wb: [644] 25 bytes
2025-10-17 13:42:36,194 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_write_metadata (recursive=False)
2025-10-17 13:42:36,195 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_write_metadata (recursive=False)
2025-10-17 13:42:36,195 - helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_write_metadata'>)
2025-10-17 13:42:36,195 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsregion - wb: [644] 9 bytes
2025-10-17 13:42:36,198 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2025-10-17 13:42:36,198 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2025-10-17 13:42:36,199 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsregion to 0:0
2025-10-17 13:42:36,199 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsdomain - wb: [644] 13 bytes
2025-10-17 13:42:36,200 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2025-10-17 13:42:36,200 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2025-10-17 13:42:36,200 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsdomain to 0:0
2025-10-17 13:42:36,200 - handlers.py[DEBUG]: finish: init-network/config-write-metadata: SUCCESS: config-write-metadata ran successfully
2025-10-17 13:42:36,200 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2025-10-17 13:42:36,201 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2025-10-17 13:42:36,201 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7fce6710ab20>)
2025-10-17 13:42:36,201 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}
2025-10-17 13:42:36,201 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2025-10-17 13:42:36,218 - util.py[DEBUG]: Reading from /proc/1448/mountinfo (quiet=False)
2025-10-17 13:42:36,218 - util.py[DEBUG]: Read 2940 bytes from /proc/1448/mountinfo
2025-10-17 13:42:36,218 - util.py[DEBUG]: Reading from /sys/class/block/nvme0n1p1/partition (quiet=False)
2025-10-17 13:42:36,218 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/nvme0n1p1/partition
2025-10-17 13:42:36,218 - util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev (quiet=False)
2025-10-17 13:42:36,218 - util.py[DEBUG]: Read 6 bytes from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev
2025-10-17 13:42:36,219 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/nvme0n1', '1'] with allowed return codes [0] (shell=False, capture=True)
2025-10-17 13:42:36,284 - util.py[DEBUG]: resize_devices took 0.067 seconds
2025-10-17 13:42:36,285 - cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/nvme0n1, 1)
2025-10-17 13:42:36,285 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2025-10-17 13:42:36,285 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2025-10-17 13:42:36,285 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2025-10-17 13:42:36,285 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7fce6710a910>)
2025-10-17 13:42:36,285 - util.py[DEBUG]: Reading from /proc/1448/mountinfo (quiet=False)
2025-10-17 13:42:36,285 - util.py[DEBUG]: Read 2940 bytes from /proc/1448/mountinfo
2025-10-17 13:42:36,286 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/nvme0n1p1 mnt_point=/ path=/
2025-10-17 13:42:36,286 - cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
2025-10-17 13:42:36,287 - util.py[DEBUG]: Forked child 1569 who will run callback log_time
2025-10-17 13:42:36,287 - cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
2025-10-17 13:42:36,287 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2025-10-17 13:42:36,287 - subp.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
2025-10-17 13:42:36,287 - modules.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance
2025-10-17 13:42:36,288 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance
2025-10-17 13:42:36,288 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_disk_setup - wb: [644] 25 bytes
2025-10-17 13:42:36,289 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_disk_setup (recursive=False)
2025-10-17 13:42:36,291 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_disk_setup (recursive=False)
2025-10-17 13:42:36,291 - helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_disk_setup'>)
2025-10-17 13:42:36,291 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully
2025-10-17 13:42:36,291 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2025-10-17 13:42:36,291 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2025-10-17 13:42:36,291 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_mounts - wb: [644] 25 bytes
2025-10-17 13:42:36,292 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_mounts (recursive=False)
2025-10-17 13:42:36,293 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_mounts (recursive=False)
2025-10-17 13:42:36,293 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_mounts'>)
2025-10-17 13:42:36,293 - cc_mounts.py[DEBUG]: mounts configuration is []
2025-10-17 13:42:36,294 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2025-10-17 13:42:36,294 - util.py[DEBUG]: Read 217 bytes from /etc/fstab
2025-10-17 13:42:36,294 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2025-10-17 13:42:36,294 - DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
2025-10-17 13:42:36,294 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2025-10-17 13:42:36,294 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2025-10-17 13:42:36,294 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2025-10-17 13:42:36,294 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2025-10-17 13:42:36,294 - cc_mounts.py[DEBUG]: changed default device swap => None
2025-10-17 13:42:36,294 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2025-10-17 13:42:36,294 - cc_mounts.py[DEBUG]: no need to setup swap
2025-10-17 13:42:36,294 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2025-10-17 13:42:36,294 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2025-10-17 13:42:36,294 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_hostname.py'>) with frequency always
2025-10-17 13:42:36,294 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency always
2025-10-17 13:42:36,294 - helpers.py[DEBUG]: Running config-set_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7fce6710ad00>)
2025-10-17 13:42:36,295 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2025-10-17 13:42:36,295 - util.py[DEBUG]: Read 76 bytes from /var/lib/cloud/data/set-hostname
2025-10-17 13:42:36,295 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2025-10-17 13:42:36,295 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2025-10-17 13:42:36,295 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2025-10-17 13:42:36,295 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2025-10-17 13:42:36,295 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7fce6710ab20>)
2025-10-17 13:42:36,295 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-172-31-3-252.ec2.internal (ip-172-31-3-252)
2025-10-17 13:42:36,295 - subp.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
2025-10-17 13:42:36,298 - __init__.py[DEBUG]: Attempting to update hostname to ip-172-31-3-252.ec2.internal in 1 files
2025-10-17 13:42:36,298 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 28 bytes
2025-10-17 13:42:36,299 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2025-10-17 13:42:36,300 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2025-10-17 13:42:36,301 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2025-10-17 13:42:36,301 - modules.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2025-10-17 13:42:36,301 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2025-10-17 13:42:36,301 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7fce6710ad00>)
2025-10-17 13:42:36,301 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts
2025-10-17 13:42:36,301 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2025-10-17 13:42:36,301 - modules.py[DEBUG]: Running module ca-certs (<module 'cloudinit.config.cc_ca_certs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ca_certs.py'>) with frequency once-per-instance
2025-10-17 13:42:36,301 - handlers.py[DEBUG]: start: init-network/config-ca-certs: running config-ca-certs with frequency once-per-instance
2025-10-17 13:42:36,302 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_ca_certs - wb: [644] 25 bytes
2025-10-17 13:42:36,302 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_ca_certs (recursive=False)
2025-10-17 13:42:36,303 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_ca_certs (recursive=False)
2025-10-17 13:42:36,303 - helpers.py[DEBUG]: Running config-ca-certs using lock (<FileLock using file '/var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_ca_certs'>)
2025-10-17 13:42:36,303 - cc_ca_certs.py[DEBUG]: Skipping module named ca-certs, no 'ca_certs' key in configuration
2025-10-17 13:42:36,303 - handlers.py[DEBUG]: finish: init-network/config-ca-certs: SUCCESS: config-ca-certs ran successfully
2025-10-17 13:42:36,304 - modules.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance
2025-10-17 13:42:36,304 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
2025-10-17 13:42:36,304 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_rsyslog - wb: [644] 25 bytes
2025-10-17 13:42:36,304 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_rsyslog (recursive=False)
2025-10-17 13:42:36,305 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_rsyslog (recursive=False)
2025-10-17 13:42:36,305 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_rsyslog'>)
2025-10-17 13:42:36,305 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
2025-10-17 13:42:36,306 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
2025-10-17 13:42:36,306 - modules.py[DEBUG]: Running module selinux (<module 'cloudinit.config.cc_selinux' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_selinux.py'>) with frequency once-per-instance
2025-10-17 13:42:36,306 - handlers.py[DEBUG]: start: init-network/config-selinux: running config-selinux with frequency once-per-instance
2025-10-17 13:42:36,306 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_selinux - wb: [644] 25 bytes
2025-10-17 13:42:36,306 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_selinux (recursive=False)
2025-10-17 13:42:36,307 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_selinux (recursive=False)
2025-10-17 13:42:36,307 - helpers.py[DEBUG]: Running config-selinux using lock (<FileLock using file '/var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_selinux'>)
2025-10-17 13:42:36,314 - cc_selinux.py[DEBUG]: Current SELinux state is enabled
2025-10-17 13:42:36,314 - cc_selinux.py[DEBUG]: Current SELinux mode is permissive
2025-10-17 13:42:36,314 - cc_selinux.py[DEBUG]: Configured SELinux mode is permissive
2025-10-17 13:42:36,314 - cc_selinux.py[DEBUG]: Current SELinux policy is targeted
2025-10-17 13:42:36,314 - cc_selinux.py[DEBUG]: No SELinux configuration, skipping
2025-10-17 13:42:36,315 - handlers.py[DEBUG]: finish: init-network/config-selinux: SUCCESS: config-selinux ran successfully
2025-10-17 13:42:36,315 - modules.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2025-10-17 13:42:36,315 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2025-10-17 13:42:36,315 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_users_groups - wb: [644] 25 bytes
2025-10-17 13:42:36,317 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_users_groups (recursive=False)
2025-10-17 13:42:36,317 - util.py[DEBUG]: backgrounded Resizing took 0.030 seconds
2025-10-17 13:42:36,318 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_users_groups (recursive=False)
2025-10-17 13:42:36,319 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_users_groups'>)
2025-10-17 13:42:36,319 - __init__.py[INFO]: User ec2-user already exists, skipping.
2025-10-17 13:42:36,320 - subp.py[DEBUG]: Running command ['passwd', '-l', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
2025-10-17 13:42:36,385 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2025-10-17 13:42:36,397 - util.py[DEBUG]: Read 4375 bytes from /etc/sudoers
2025-10-17 13:42:36,399 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d (recursive=False)
2025-10-17 13:42:36,400 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - ab: [None] 59 bytes
2025-10-17 13:42:36,409 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d/90-cloud-init-users (recursive=False)
2025-10-17 13:42:36,410 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2025-10-17 13:42:36,410 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2025-10-17 13:42:36,410 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2025-10-17 13:42:36,411 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_ssh - wb: [644] 24 bytes
2025-10-17 13:42:36,411 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_ssh (recursive=False)
2025-10-17 13:42:36,412 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_ssh (recursive=False)
2025-10-17 13:42:36,413 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_ssh'>)
2025-10-17 13:42:36,413 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2025-10-17 13:42:36,433 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2025-10-17 13:42:36,439 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2025-10-17 13:42:36,447 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2025-10-17 13:42:36,452 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2025-10-17 13:42:36,452 - util.py[DEBUG]: Read 115 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2025-10-17 13:42:36,452 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2025-10-17 13:42:36,452 - util.py[DEBUG]: Read 195 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2025-10-17 13:42:36,453 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-10-17 13:42:36,453 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2025-10-17 13:42:36,454 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 1000:1000
2025-10-17 13:42:36,455 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=False)
2025-10-17 13:42:36,455 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2025-10-17 13:42:36,455 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-10-17 13:42:36,455 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-10-17 13:42:36,456 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 1000:1000
2025-10-17 13:42:36,456 - util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
2025-10-17 13:42:36,456 - util.py[DEBUG]: Read 0 bytes from /home/ec2-user/.ssh/authorized_keys
2025-10-17 13:42:36,456 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2025-10-17 13:42:36,456 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-10-17 13:42:36,456 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2025-10-17 13:42:36,456 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=True)
2025-10-17 13:42:36,457 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-10-17 13:42:36,458 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2025-10-17 13:42:36,458 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2025-10-17 13:42:36,459 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2025-10-17 13:42:36,459 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-10-17 13:42:36,459 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-10-17 13:42:36,460 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2025-10-17 13:42:36,460 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2025-10-17 13:42:36,460 - util.py[DEBUG]: Read 0 bytes from /root/.ssh/authorized_keys
2025-10-17 13:42:36,460 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2025-10-17 13:42:36,460 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-10-17 13:42:36,460 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2025-10-17 13:42:36,460 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2025-10-17 13:42:36,461 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2025-10-17 13:42:36,461 - main.py[DEBUG]: Ran 17 modules with 0 failures
2025-10-17 13:42:36,462 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpar247ivx) - w: [644] 486 bytes/chars
2025-10-17 13:42:36,462 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-10-17 13:42:36,462 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2025-10-17 13:42:36,462 - util.py[DEBUG]: cloud-init mode 'init' took 1.107 seconds (1.10)
2025-10-17 13:42:36,462 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2025-10-17 13:42:37,052 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:config' at Fri, 17 Oct 2025 13:42:36 +0000. Up 8.59 seconds.
2025-10-17 13:42:37,058 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:37,058 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:37,061 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:37,061 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:37,063 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:37,063 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:37,065 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:37,066 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:37,068 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:37,068 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:37,070 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:37,070 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:37,073 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:37,073 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:37,075 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:37,075 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:37,077 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:37,077 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:37,079 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:37,079 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:37,081 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-10-17 13:42:37,081 - modules.py[INFO]: Skipping modules 'ssh-import-id' because they are not verified on distro 'amazon'.  To run anyway, add them to 'unverified_modules' in config.
2025-10-17 13:42:37,081 - modules.py[DEBUG]: Running module keyboard (<module 'cloudinit.config.cc_keyboard' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_keyboard.py'>) with frequency once-per-instance
2025-10-17 13:42:37,081 - handlers.py[DEBUG]: start: modules-config/config-keyboard: running config-keyboard with frequency once-per-instance
2025-10-17 13:42:37,082 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_keyboard - wb: [644] 25 bytes
2025-10-17 13:42:37,083 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_keyboard (recursive=False)
2025-10-17 13:42:37,086 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_keyboard (recursive=False)
2025-10-17 13:42:37,087 - helpers.py[DEBUG]: Running config-keyboard using lock (<FileLock using file '/var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_keyboard'>)
2025-10-17 13:42:37,087 - cc_keyboard.py[DEBUG]: Skipping module named keyboard, no 'keyboard' section found
2025-10-17 13:42:37,087 - handlers.py[DEBUG]: finish: modules-config/config-keyboard: SUCCESS: config-keyboard ran successfully
2025-10-17 13:42:37,087 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2025-10-17 13:42:37,087 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2025-10-17 13:42:37,088 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_locale - wb: [644] 24 bytes
2025-10-17 13:42:37,088 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_locale (recursive=False)
2025-10-17 13:42:37,089 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_locale (recursive=False)
2025-10-17 13:42:37,090 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_locale'>)
2025-10-17 13:42:37,090 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2025-10-17 13:42:37,090 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2025-10-17 13:42:37,090 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2025-10-17 13:42:37,090 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2025-10-17 13:42:37,090 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2025-10-17 13:42:37,090 - util.py[DEBUG]: Writing to /etc/locale.conf - wb: [644] 17 bytes
2025-10-17 13:42:37,093 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2025-10-17 13:42:37,097 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2025-10-17 13:42:37,097 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2025-10-17 13:42:37,097 - modules.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2025-10-17 13:42:37,097 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2025-10-17 13:42:37,098 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_set_passwords - wb: [644] 25 bytes
2025-10-17 13:42:37,098 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_set_passwords (recursive=False)
2025-10-17 13:42:37,099 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_set_passwords (recursive=False)
2025-10-17 13:42:37,099 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_set_passwords'>)
2025-10-17 13:42:37,099 - subp.py[DEBUG]: Running command ['systemctl', 'status', 'sshd'] with allowed return codes [0] (shell=False, capture=True)
2025-10-17 13:42:37,118 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2025-10-17 13:42:37,118 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2025-10-17 13:42:37,119 - ssh_util.py[DEBUG]: line 65: option PasswordAuthentication already set to no
2025-10-17 13:42:37,119 - cc_set_passwords.py[DEBUG]: No need to restart SSH service, PasswordAuthentication not updated.
2025-10-17 13:42:37,119 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2025-10-17 13:42:37,119 - modules.py[DEBUG]: Running module yum-variables (<module 'cloudinit.config.cc_yum_variables' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_variables.py'>) with frequency once-per-instance
2025-10-17 13:42:37,119 - handlers.py[DEBUG]: start: modules-config/config-yum-variables: running config-yum-variables with frequency once-per-instance
2025-10-17 13:42:37,120 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_yum_variables - wb: [644] 25 bytes
2025-10-17 13:42:37,121 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_yum_variables (recursive=False)
2025-10-17 13:42:37,122 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_yum_variables (recursive=False)
2025-10-17 13:42:37,122 - helpers.py[DEBUG]: Running config-yum-variables using lock (<FileLock using file '/var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_yum_variables'>)
2025-10-17 13:42:37,122 - cc_yum_variables.py[INFO]: handling yum-variables
2025-10-17 13:42:37,122 - cc_yum_variables.py[INFO]: cfg = {'cloud_final_modules': [['scripts-user', 'always']], 'repo_releasever': 2023.9, 'repo_upgrade': 'none', 'power_state': {'delay': 'now', 'mode': 'reboot', 'message': 'Rebooting machine to apply SELinux kernel commandline setting', 'condition': 'test -f /run/cloud-init-selinux-reboot'}, 'write_metadata': [{'path': '/etc/dnf/vars/awsregion', 'data': [{'identity': 'region'}, 'default']}, {'path': '/etc/dnf/vars/awsdomain', 'data': [{'metadata': 'services/domain'}, 'amazonaws.com']}], '_log': ['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n", '[handler_cloudLogHandler]\nclass=handlers.SysLogHandler\nlevel=DEBUG\nformatter=simpleFormatter\nargs=("/dev/log", handlers.SysLogHandler.LOG_USER)\n'], 'log_cfgs': [['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n"]], 'output': {'all': '| tee -a /var/log/cloud-init-output.log'}, 'network': {'config': 'disabled'}, 'datasource_list': ['Ec2', 'None'], 'datasource': {'Ec2': {'metadata_urls': ['http://169.254.169.254:80', 'http://[fd00:ec2::254]:80'], 'apply_full_imds_network_config': False}}, 'ssh_genkeytypes': ['ed25519', 'ecdsa'], 'users': ['default'], 'disable_root': True, 'mount_default_fields': [None, None, 'auto', 'defaults,nofail', '0', '2'], 'resize_rootfs': 'noblock', 'resize_rootfs_tmp': '/dev', 'ssh_pwauth': False, 'preserve_hostname': False, 'cloud_init_modules': ['migrator', 'seed_random', 'bootcmd', 'write-files', 'write-metadata', 'growpart', 'resizefs', 'disk_setup', 'mounts', 'set_hostname', 'update_hostname', 'update_etc_hosts', 'ca-certs', 'rsyslog', 'selinux', 'users-groups', 'ssh'], 'cloud_config_modules': ['ssh-import-id', 'keyboard', 'locale', 'set-passwords', 'yum-variables', 'yum-add-repo', 'ntp', 'timezone', 'disable-ec2-metadata', 'runcmd'], 'def_log_file': '/var/log/cloud-init.log', 'syslog_fix_perms': ['syslog:adm', 'root:adm', 'root:wheel', 'root:root'], 'vendor_data': {'enabled': True, 'prefix': []}, 'vendor_data2': {'enabled': True, 'prefix': []}}
2025-10-17 13:42:37,123 - cc_yum_variables.py[INFO]: No yum vars to delete
2025-10-17 13:42:37,123 - cc_yum_variables.py[INFO]: No yum vars to set
2025-10-17 13:42:37,123 - handlers.py[DEBUG]: finish: modules-config/config-yum-variables: SUCCESS: config-yum-variables ran successfully
2025-10-17 13:42:37,123 - modules.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_add_repo.py'>) with frequency once-per-instance
2025-10-17 13:42:37,123 - handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
2025-10-17 13:42:37,123 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_yum_add_repo - wb: [644] 25 bytes
2025-10-17 13:42:37,123 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_yum_add_repo (recursive=False)
2025-10-17 13:42:37,124 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_yum_add_repo (recursive=False)
2025-10-17 13:42:37,124 - helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_yum_add_repo'>)
2025-10-17 13:42:37,124 - cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
2025-10-17 13:42:37,125 - handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully
2025-10-17 13:42:37,125 - modules.py[DEBUG]: Running module ntp (<module 'cloudinit.config.cc_ntp' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ntp.py'>) with frequency once-per-instance
2025-10-17 13:42:37,125 - handlers.py[DEBUG]: start: modules-config/config-ntp: running config-ntp with frequency once-per-instance
2025-10-17 13:42:37,125 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_ntp - wb: [644] 25 bytes
2025-10-17 13:42:37,125 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_ntp (recursive=False)
2025-10-17 13:42:37,126 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_ntp (recursive=False)
2025-10-17 13:42:37,126 - helpers.py[DEBUG]: Running config-ntp using lock (<FileLock using file '/var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_ntp'>)
2025-10-17 13:42:37,126 - cc_ntp.py[DEBUG]: Skipping module named ntp, not present or disabled by cfg
2025-10-17 13:42:37,126 - handlers.py[DEBUG]: finish: modules-config/config-ntp: SUCCESS: config-ntp ran successfully
2025-10-17 13:42:37,126 - modules.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2025-10-17 13:42:37,126 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2025-10-17 13:42:37,127 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_timezone - wb: [644] 24 bytes
2025-10-17 13:42:37,127 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_timezone (recursive=False)
2025-10-17 13:42:37,128 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_timezone (recursive=False)
2025-10-17 13:42:37,128 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_timezone'>)
2025-10-17 13:42:37,128 - cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
2025-10-17 13:42:37,128 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
2025-10-17 13:42:37,129 - modules.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disable_ec2_metadata.py'>) with frequency always
2025-10-17 13:42:37,129 - handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
2025-10-17 13:42:37,129 - helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7f828ea1cf70>)
2025-10-17 13:42:37,129 - cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
2025-10-17 13:42:37,129 - handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
2025-10-17 13:42:37,129 - modules.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_runcmd.py'>) with frequency once-per-instance
2025-10-17 13:42:37,129 - handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
2025-10-17 13:42:37,129 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_runcmd - wb: [644] 24 bytes
2025-10-17 13:42:37,130 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_runcmd (recursive=False)
2025-10-17 13:42:37,130 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_runcmd (recursive=False)
2025-10-17 13:42:37,130 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-0d445e9a3d91a5047/sem/config_runcmd'>)
2025-10-17 13:42:37,130 - cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
2025-10-17 13:42:37,131 - handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
2025-10-17 13:42:37,131 - main.py[DEBUG]: Ran 9 modules with 0 failures
2025-10-17 13:42:37,131 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpo3dtb7_j) - w: [644] 514 bytes/chars
2025-10-17 13:42:37,131 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-10-17 13:42:37,131 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2025-10-17 13:42:37,131 - util.py[DEBUG]: cloud-init mode 'modules' took 0.181 seconds (0.18)
2025-10-17 13:42:37,131 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2025-10-17 13:42:37,657 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:final' at Fri, 17 Oct 2025 13:42:37 +0000. Up 9.22 seconds.
2025-10-17 13:42:37,660 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2025-10-17 13:42:37,661 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2025-10-17 13:42:37,662 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2025-10-17 13:42:37,663 - modules.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_user.py'>) with frequency always
2025-10-17 13:42:37,663 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency always
2025-10-17 13:42:37,663 - helpers.py[DEBUG]: Running config-scripts-user using lock (<cloudinit.helpers.DummyLock object at 0x7ff86ae8a640>)
2025-10-17 13:42:37,663 - subp.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/user-data.txt'] with allowed return codes [0] (shell=False, capture=False)
2025-10-17 13:42:49,773 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2025-10-17 13:42:49,773 - main.py[DEBUG]: Ran 1 modules with 0 failures
2025-10-17 13:42:49,774 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpubocpt0u) - w: [644] 542 bytes/chars
2025-10-17 13:42:49,774 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmpi_kmzwem) - w: [644] 64 bytes/chars
2025-10-17 13:42:49,774 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2025-10-17 13:42:49,774 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-10-17 13:42:49,774 - util.py[DEBUG]: Read 12 bytes from /proc/uptime
2025-10-17 13:42:49,774 - util.py[DEBUG]: cloud-init mode 'modules' took 12.191 seconds (12.13)
2025-10-17 13:42:49,775 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
